
---
title: "maps"
author: "Heather Hochrein and Juliana Matos"
date: "December 4, 2015"
output: html_document
---
## Create Map of Points
```{r}



# load packages
suppressWarnings(suppressPackageStartupMessages({
  library(leaflet)
  library(rgdal)
}))

# set paths
gdb = 'H:/esm296-4f/lab3/golf.gdb'

# read points from geodatabase
pts = readOGR(gdb, 'pts_tree', verbose=F)

# project points to geographic projection
pts_gcs = spTransform(pts, leaflet:::epsg4326)

# create map of points
leaflet() %>%
  addTiles() %>%
  addMarkers(data = pts_gcs)

```

# Create Map with Popups
```{r}



leaflet() %>%
  addTiles() %>%
  addMarkers(data = pts_gcs, popup=~sprintf('id: %d', id)) 

```

# Create Map with Stamen.Watercolor basemap
```{r}

leaflet() %>%  
  addProviderTiles('Stamen.Watercolor') %>%
  addMarkers(data = pts_gcs, popup=~sprintf('id: %d', id))
```

# create map with Stamen.Toner basemap
```{r}

leaflet() %>%  
  addProviderTiles('Stamen.Toner') %>%
  addMarkers(data = pts_gcs, popup=~sprintf('id: %d', id))
```

# create map with Esri.WorldPhysical basemap
```{r}


leaflet() %>%  
  addProviderTiles('Esri.WorldPhysical') %>%
  addMarkers(data = pts_gcs, popup=~sprintf('id: %d', id))

```

# map with lines and polygons
```{r}
# read points, lines and polygons from geodatabase
pts_gcs  = readOGR(gdb, 'pts_tree', verbose=F)    %>% spTransform(leaflet:::epsg4326)
lns_gcs  = readOGR(gdb, 'lns_cart', verbose=F)    %>% spTransform(leaflet:::epsg4326)
plys_gcs = readOGR(gdb, 'plys_bunker', verbose=F) %>% spTransform(leaflet:::epsg4326)


leaflet() %>%  
  addProviderTiles('Stamen.Toner') %>%
  addPolygons(color= "yellow", stroke= FALSE, data=plys_gcs) %>%  
  addPolylines(data=lns_gcs) %>%
  addMarkers(data=pts_gcs, popup=~sprintf('id: %d', id))
```

# map with raster
```{r}
# set path to your final chosen classified image
library(raster)
tif = 'H:/esm296-4f/lab3/images_rect/vid_sec157_5.tif'
  
# read raster, presumably in Web Mercator
r = raster(tif, crs = leaflet:::epsg3857)

# setup color palette
pal = colorFactor('Set3', values(r), na.color='transparent')


leaflet() %>%  
  addProviderTiles('Stamen.Toner') %>%
  addRasterImage(r, colors=pal,opacity = 0.6, project=F) %>%
  addLegend(pal=pal, values=values(r), title='Habitats')
```

